# Generated by Django 2.0.5 on 2018-05-30 19:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0012_auto_20180523_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 19, 56, 40, 296739), editable=False),
        ),
        migrations.AddField(
            model_name='answergps',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 19, 56, 40, 298238), editable=False),
        ),
        migrations.AddField(
            model_name='answergs',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 19, 56, 40, 298739), editable=False),
        ),
        migrations.AddField(
            model_name='answerhhmembers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 19, 56, 40, 299739), editable=False),
        ),
        migrations.AddField(
            model_name='answernr',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 19, 56, 40, 300743), editable=False),
        ),
        migrations.AddField(
            model_name='price',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 19, 56, 40, 301242), editable=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('20277b4d-cca9-4708-87e3-58d128ce5eda'), editable=False, primary_key=True, serialize=False),
        ),
    ]
