# Generated by Django 2.0.5 on 2018-05-31 15:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0016_ame_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMEPerDistrict',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_owner', models.TextField(blank=True, null=True)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_hh_ame', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_hh_ame', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_ame_per_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AMEPerHH',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_owner', models.TextField()),
                ('hh_id', models.TextField()),
                ('dataset_year', models.IntegerField(null=True)),
                ('village', models.TextField()),
                ('district', models.TextField()),
                ('landscape', models.TextField()),
                ('hh_ame', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
            ],
            options={
                'db_table': 'bns_ame_per_hh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AMEPerLandscape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_owner', models.TextField(blank=True, null=True)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_hh_ame', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_hh_ame', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_ame_per_landscape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AMEPerVillage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_owner', models.TextField(blank=True, null=True)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_hh_ame', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_hh_ame', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_ame_per_village',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('51cb656c-ed21-4ec3-b803-189a663e5254'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 54, 30, 938073), editable=False),
        ),
        migrations.AlterField(
            model_name='answergps',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 54, 30, 938573), editable=False),
        ),
        migrations.AlterField(
            model_name='answergs',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 54, 30, 939073), editable=False),
        ),
        migrations.AlterField(
            model_name='answerhhmembers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 54, 30, 939574), editable=False),
        ),
        migrations.AlterField(
            model_name='answernr',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 54, 30, 940074), editable=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 15, 54, 30, 940573), editable=False),
        ),
    ]
