# Generated by Django 2.0.5 on 2018-06-10 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0023_ethnicity_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthnicityPerDistrict',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('ethnicity', models.TextField(blank=True, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_ethnicity_per_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EthnicityPerLandscape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('ethnicity', models.TextField(blank=True, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_ethnicity_per_landscape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EthnicityPerVillage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('ethnicity', models.TextField(blank=True, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_ethnicity_per_village',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('632a9651-ad22-47f9-8dfd-84a92068281f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
