# Generated by Django 2.0.5 on 2018-09-12 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0035_wbi_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBIPerDistrict',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_wbi', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_wbi', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_wbi_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WBIPerHousehold',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('hh_id', models.TextField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('livelihood_1', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('ethnicity', models.TextField(blank=True, null=True)),
                ('hh_type_control', models.NullBooleanField()),
                ('hh_type_org_benef', models.NullBooleanField()),
                ('hh_type_other_benef', models.NullBooleanField()),
                ('hh_score', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('wbi', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
            ],
            options={
                'db_table': 'bns_wbi_hh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WBIPerLandscape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_wbi', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_wbi', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_wbi_landscape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WBIPerVillage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_wbi', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_wbi', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_wbi_village',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('ce62eda5-3ab0-4d6b-b5b4-bc90f42f4531'), editable=False, primary_key=True, serialize=False),
        ),
    ]
