# Generated by Django 2.0.5 on 2018-09-12 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0037_add_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('701feddd-f950-43c3-8152-0e2e31ff1b96'), editable=False, primary_key=True, serialize=False),
        ),
    ]
