# Generated by Django 2.0.5 on 2018-09-14 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0051_bns_form_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNSForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.TextField(blank=True, null=True)),
                ('dataset_year', models.TextField(blank=True, null=True)),
                ('dataset_owner', models.TextField(blank=True, null=True)),
                ('dataset_uuid', models.TextField(blank=True, null=True)),
                ('last_submission_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('last_update_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('last_checked_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'BNS Form',
                'verbose_name_plural': 'BNS Forms',
                'db_table': 'bns_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BNSFormPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.TextField(blank=True, null=True)),
                ('related_dataset', models.TextField(blank=True, null=True)),
                ('dataset_year', models.TextField(blank=True, null=True)),
                ('dataset_owner', models.TextField(blank=True, null=True)),
                ('dataset_uuid', models.TextField(blank=True, null=True)),
                ('last_submission_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('last_update_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('last_checked_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'BNS Form',
                'verbose_name_plural': 'BNS Forms',
                'db_table': 'bns_form_price',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='answergps',
            options={'verbose_name': 'Answer - GPS', 'verbose_name_plural': 'Answers - GPS'},
        ),
        migrations.AlterModelOptions(
            name='answergs',
            options={'verbose_name': 'Answer - Good or Service', 'verbose_name_plural': 'Answers - Goods and Services'},
        ),
        migrations.AlterModelOptions(
            name='answerhhmembers',
            options={'verbose_name': 'Answer - HH Members', 'verbose_name_plural': 'Answers - HH Members'},
        ),
        migrations.AlterModelOptions(
            name='answernr',
            options={'verbose_name': 'Answer - Natural Resource', 'verbose_name_plural': 'Answers - Natural Resources'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Answer - Price', 'verbose_name_plural': 'Answers - Prices'},
        ),
    ]
