# Generated by Django 2.0.5 on 2018-05-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
