# Generated by Django 2.0.5 on 2018-05-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0007_answer_dataset_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dataset_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kobo.KoboData'),
        ),
    ]
