# Generated by Django 2.0.5 on 2018-05-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0009_auto_20180521_2222'),
        ('bns', '0011_auto_20180523_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.TextField()),
                ('surveyor', models.TextField(blank=True, null=True)),
                ('gs', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('dataset_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kobo.KoboData')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('dataset_uuid', 'village', 'gs')},
        ),
    ]
