# Generated by Django 2.0.5 on 2018-05-30 20:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0013_auto_20180530_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ame',
            name='gender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('0b90bc6c-a449-467f-ad52-80ec21a875be'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='bns_plus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='explain_benef_pa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='explain_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='hh_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='landscape',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 20, 56, 17, 164419), editable=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='livelihood_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='livelihood_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='livelihood_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='livelihood_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='participant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='surveyor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='village',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answergps',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 20, 56, 17, 164419), editable=False),
        ),
        migrations.AlterField(
            model_name='answergs',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 20, 56, 17, 164419), editable=False),
        ),
        migrations.AlterField(
            model_name='answerhhmembers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 20, 56, 17, 167417), editable=False),
        ),
        migrations.AlterField(
            model_name='answernr',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 20, 56, 17, 167417), editable=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 20, 56, 17, 167417), editable=False),
        ),
    ]
