# Generated by Django 2.0.5 on 2018-05-31 11:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0014_auto_20180530_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('e5ec14b2-c4b2-4b7d-acff-d2eef7c2fe6f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 11, 7, 38, 831234), editable=False),
        ),
        migrations.AlterField(
            model_name='answergps',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 11, 7, 38, 831234), editable=False),
        ),
        migrations.AlterField(
            model_name='answergs',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 11, 7, 38, 831234), editable=False),
        ),
        migrations.AlterField(
            model_name='answerhhmembers',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 11, 7, 38, 831234), editable=False),
        ),
        migrations.AlterField(
            model_name='answernr',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 11, 7, 38, 831234), editable=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 31, 11, 7, 38, 831234), editable=False),
        ),
    ]
