# Generated by Django 2.0.5 on 2018-06-04 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0019_ame_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('174a9131-a2ab-4928-ace4-b9a10b54899e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
