# Generated by Django 2.0.5 on 2018-06-10 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0026_gender_head_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderHeadPerDistrict',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_gender_head_per_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenderHeadPerLandscape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_gender_head_per_landscape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenderHeadPerVillage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_gender_head_per_village',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('05f457f1-a2d0-4639-8506-ac3f1e4fdcd2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
