# Generated by Django 2.0.5 on 2018-06-10 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0029_livelihood_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivelihoodNBPerDistrict',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_lh_number', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_lh_number', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_livelihood_nb_per_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivelihoodNBPerLandscape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_lh_number', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_lh_number', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_livelihood_nb_per_landscape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LivelihoodNBPerVillage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_lh_number', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_lh_number', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_livelihood_nb_per_village',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('4099d6d8-f734-4005-836d-1ed5253ac03a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
