# Generated by Django 2.0.5 on 2018-06-24 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0033_pa_project_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAProjectsPerDistrict',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('perc_benef_project', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('perc_know_pa', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('perc_benef_pa', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_project_pa_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PAProjectsPerLandscape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('perc_benef_project', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('perc_know_pa', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('perc_benef_pa', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_project_pa_landscape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PAProjectsPerVillage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('perc_benef_project', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('perc_know_pa', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('perc_benef_pa', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bns_project_pa_village',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('57d04fc7-02cc-4d25-8850-0215fd4de70f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
