# Generated by Django 2.0.5 on 2018-09-13 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0039_wbi_views_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.UUIDField(default=uuid.UUID('04d1f7a1-ae31-4ebc-b7da-7e8dd08a5fa9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
