# Generated by Django 2.0.5 on 2018-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0047_wealth_idx_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='WealthIdxPerDistrict',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_wealth_idx', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_wealth_idx', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
            ],
            options={
                'db_table': 'bns_wealth_idx_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WealthIdxPerHH',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('hh_id', models.TextField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('wealth_idx', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
            ],
            options={
                'db_table': 'bns_wealth_idx_hh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WealthIdxPerLandscape',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_wealth_idx', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_wealth_idx', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
            ],
            options={
                'db_table': 'bns_wealth_idx_landscape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WealthIdxPerVillage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('avg_wealth_idx', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('stddev_wealth_idx', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('n', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
            ],
            options={
                'db_table': 'bns_wealth_idx_village',
                'managed': False,
            },
        ),
    ]
