# Generated by Django 2.0.5 on 2018-09-14 12:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0049_wbi_diff_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBIPerHHDiff20152017',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('hh_id', models.TextField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('hh_type_control', models.NullBooleanField()),
                ('hh_type_org_benef', models.NullBooleanField()),
                ('hh_type_other_benef', models.NullBooleanField()),
                ('wbi_2015', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('wbi_2017', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('wbi_diff', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'bns_wbi_hh_diff_2015_2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WBIPerVillageDiff20152017',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('hh_id', models.TextField(blank=True, null=True)),
                ('village', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('hh_type_control', models.NullBooleanField()),
                ('wbi_2015', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('wbi_2017', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('wbi_diff', models.DecimalField(blank=True, decimal_places=6, max_digits=29, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'bns_wbi_village_diff_2015_2017',
                'managed': False,
            },
        ),
    ]
