# Generated by Django 2.0.5 on 2018-09-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0053_update_bns_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bnsformprice',
            options={'managed': False, 'verbose_name': 'BNS Form - Price', 'verbose_name_plural': 'BNS Forms - Prices'},
        ),
    ]
