# Generated by Django 2.0.5 on 2018-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns', '0058_update_form_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerhhmembers',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
