# Generated by Django 2.1.3 on 2018-11-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nrgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NRGTAnswerGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('survey_date', models.DateTimeField(blank=True, null=True)),
                ('member', models.NullBooleanField()),
                ('gender', models.TextField(blank=True, null=True)),
                ('motivation', models.IntegerField(blank=True, null=True)),
                ('instutional_framework', models.IntegerField(blank=True, null=True)),
                ('fairness', models.IntegerField(blank=True, null=True)),
                ('enact_decision', models.IntegerField(blank=True, null=True)),
                ('knowledge_skills', models.IntegerField(blank=True, null=True)),
                ('participation', models.IntegerField(blank=True, null=True)),
                ('transparency', models.IntegerField(blank=True, null=True)),
                ('resources', models.IntegerField(blank=True, null=True)),
                ('diversity', models.IntegerField(blank=True, null=True)),
                ('held_accountable', models.IntegerField(blank=True, null=True)),
                ('accountability', models.IntegerField(blank=True, null=True)),
                ('legitimacy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Answer Governance Score',
                'verbose_name_plural': 'Answers Governance Score',
            },
        ),
        migrations.AddField(
            model_name='nrgtanswer',
            name='gov_group',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrgtanswer',
            name='jurisdiction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrgtanswer',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrgtanswer',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrgtanswer',
            name='women',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrgtanswergs',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nrgt.NRGTAnswer'),
        ),
    ]
