# Generated by Django 2.1.3 on 2018-11-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrgt', '0005_nrgt_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='NRGTGroupAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscape', models.TextField(blank=True, null=True)),
                ('gov_group', models.TextField(blank=True, null=True)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('autority', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('power', models.FloatField(blank=True, null=True)),
                ('diversity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NRGT Group Attribute',
                'verbose_name_plural': 'NRGT Group Attributes',
                'db_table': 'nrgt_group_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NRGTGroupScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscape', models.TextField(blank=True, null=True)),
                ('gov_group', models.TextField(blank=True, null=True)),
                ('dataset_year', models.IntegerField(blank=True, null=True)),
                ('legitimacy', models.FloatField(blank=True, null=True)),
                ('accountability', models.FloatField(blank=True, null=True)),
                ('transparency', models.FloatField(blank=True, null=True)),
                ('participation', models.FloatField(blank=True, null=True)),
                ('instutional_framework', models.FloatField(blank=True, null=True)),
                ('fairness', models.FloatField(blank=True, null=True)),
                ('motivation', models.FloatField(blank=True, null=True)),
                ('knowledge_skills', models.FloatField(blank=True, null=True)),
                ('resources', models.FloatField(blank=True, null=True)),
                ('held_accountable', models.FloatField(blank=True, null=True)),
                ('enact_decision', models.FloatField(blank=True, null=True)),
                ('diversity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NRGT Group Score',
                'verbose_name_plural': 'NRGT Group Scores',
                'db_table': 'nrgt_group_scores',
                'managed': False,
            },
        ),
    ]
