# Generated by Django 2.1.3 on 2018-11-09 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrgt', '0006_nrgtgroupattributes_nrgtgroupscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='nrgtanswergs',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
