# Generated by Django 2.0.5 on 2018-09-19 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kobo', '0012_auto_20180914_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='NRGTAnswer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('landscape', models.TextField(blank=True, null=True)),
                ('surveyor', models.TextField(blank=True, null=True)),
                ('survey_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('dataset_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kobo.KoboData')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
