# Generated by Django 2.0.5 on 2018-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('auth_user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('auth_pass', models.CharField(max_length=200)),
                ('host_assets', models.CharField(max_length=200)),
                ('host_api', models.CharField(max_length=200)),
            ],
        ),
    ]
