# Generated by Django 2.0.5 on 2018-05-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Connection',
        ),
    ]
