# Generated by Django 2.0.5 on 2018-05-09 22:27

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0003_kobodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kobodata',
            name='dataset_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kobodata',
            name='dataset_owner',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kobodata',
            name='dataset_uuid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kobodata',
            name='dataset_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kobodata',
            name='last_submission_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='kobodata',
            name='dataset',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='kobodata',
            name='dataset_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kobodata',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=None),
        ),
    ]
