# Generated by Django 2.0.5 on 2018-05-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0006_connection_last_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobodata',
            name='id',
        ),
        migrations.AlterField(
            model_name='kobodata',
            name='dataset_uuid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
