# Generated by Django 2.0.5 on 2018-05-21 19:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0007_auto_20180521_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobodata',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
    ]
