# Generated by Django 2.0.5 on 2018-09-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0012_auto_20180914_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='kobodata',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kobodata',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kobo.Connection'),
        ),
    ]
