# Generated by Django 2.1.3 on 2018-11-19 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0014_auto_20180921_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='kobodata',
            name='last_checked_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='kobodata',
            name='last_update_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
