# Generated by Django 2.1.4 on 2018-12-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0016_kobouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobouser',
            name='surveys',
        ),
        migrations.AddField(
            model_name='kobouser',
            name='surveys',
            field=models.ManyToManyField(to='kobo.KoboData'),
        ),
    ]
