# Generated by Django 2.1.4 on 2018-12-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0017_auto_20181220_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobouser',
            name='surveys',
            field=models.ManyToManyField(blank=True, to='kobo.KoboData'),
        ),
    ]
