# Generated by Django 2.0.5 on 2018-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0004_auto_20180509_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobodata',
            name='dataset',
        ),
        migrations.AddField(
            model_name='kobodata',
            name='last_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
