# Generated by Django 2.0.5 on 2018-05-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0008_auto_20180521_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kobodata',
            options={'verbose_name': 'Kobo data', 'verbose_name_plural': 'Kobo data'},
        ),
    ]
