# Generated by Django 2.0.5 on 2018-05-31 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0010_kobodata_last_checked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobodata',
            name='last_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
