# Generated by Django 2.0.5 on 2018-09-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0011_auto_20180531_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kobodata',
            options={'verbose_name': 'Kobo form', 'verbose_name_plural': 'Kobo forms'},
        ),
    ]
