# Generated by Django 2.0.5 on 2018-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kobo', '0013_auto_20180921_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kobodata',
            name='legacy',
        ),
        migrations.AddField(
            model_name='kobodata',
            name='kobo_managed',
            field=models.BooleanField(default=True),
        ),
    ]
